### ISSUE TITLE
Differences between linear regression & decision trees

### ISSUE THREAD

**Issue by koyegbeke** [InseadDataAnalytics/INSEADAnalytics#114]
This is a very general question, but under what circumstances is it better to use a linear regression model [lm ()] versus a decision tree [rpart ()]?

**Comment by VivianZhang0721** [comment]
If I don't know my data well and don't have strong assumptions, and when I have a fair amount of variables, I would use both model and evaluate their prediction performance (MSE, AUC, Sensitivity, Specificity...)

**Comment by samjameswaller** [comment]
When the data has a linear shape you can use the linear regression model, but when the data has a non-linear shape, then a linear model cannot capture the non-linear features.

So in this case, you can use the decision trees, which do a better job at capturing the non-linearity in the data by dividing the space into smaller sub-spaces depending on the questions asked...

I have also read that regressions handle noise better than random forests, because decision trees are discrete models, but remember that linear regression have some pre-assumptions such as normality of resuduals, homoscedasticity

**Comment by AndreaSiri** [comment]
Furthermore, if I have understood your question correctly, linear regressions do not perform very well with binary dependent variables (0,1), whereas in that case it is better to use other functions like ctree or logistic.

**Comment by koyegbeke** [comment]
Thank you.
