### ISSUE TITLE
Kintting to HTML ExerciseSet1.RMD (and Error in source("dataSet1.R"))

### ISSUE THREAD

**Issue by Sefimenko** [InseadDataAnalytics/INSEADAnalytics#8]
1. For those who had a problem in knitting to HTML your version of ExerciseSet1.RMD. There was a problem with a package called "vegan". I solved it by googling this error and uploading some update for OS on my mac. 
2. Now I have the following error when I tried to knit the file: 
![screen shot 2016-01-12 at 22 04 51](https://cloud.githubusercontent.com/assets/16547104/12276882/932db26e-b978-11e5-81c1-f93acf397e0d.png)

It says that there is a Error in source("dataSet1.R"), probably I should change smth in  "dataSet1.R". How can I solve this issue?

**Comment by tevgeniou** [comment]
In general:
1.make sure you are in the right directory. 
2. it is usually a good idea to run the code step by step sometimes - to see where the problem may be. In this case open the dataset1.R file and run these lines first (which are now commented out):
rm(list=ls()) # Clean up the memory, if we want to rerun from scratch
source("helpersSet1.R")
(if the problem is in the second line, open the helpersSet1.R and source it to see where the problem is). 
then run all remaining code of dataset1.R to see where the issue is - if any. You can highlight any part of code and click on "Run" to run only that part, or click on "Source" to run the whole .R file.

**Comment by Sefimenko** [comment]
I solved the problem. As dar as I understand two things should be done to knit:
1) in row 8 of the code add " for "GS" ticker
2) load the library: 
> library(quantmod) 
> getSymbols("YHOO",src="google")
