### ISSUE TITLE
How to change the label of a chart (e.g., Data etc.)

### ISSUE THREAD

**Issue by AndreaSiri** [InseadDataAnalytics/INSEADAnalytics#85]
Dear all,

Do you know how to change the way data show up on the charts? (e.g., date as 40400 etc instead of April/2010).

Best,
Andrea

**Comment by vrroldao** [comment]
you can use the the options "xlab" and "ylab"
e.g.:
`plot(data, xlab="Month", ylab="data")`

**Comment by Antoine-Engerand** [comment]
I found multiple ways to do it but this is the simplest: convert the first Date column into characters instead of integers.

Indeed, if you type the command typeof(exhibit.1$Dates), it will show: integer (hence the 40400, etc.). Using this code I can convert the first column to characters (strings):

`exhibit.1 %>% mutate(Date = as.character(Date)) -> exhibit.1`

Any other solution? Does it answer your question @AndreaSiri & @pgmorgan ?

**Comment by AndreaSiri** [comment]
Dear all, 

Thank you all for the suggestion.

@Antoine-Engerand seems reply to work!

Best,
Andrea
